// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewFile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function ExportHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportHTML'](arg1, arg2);
}

export function GetInitialFiles() {
  return window['go']['main']['App']['GetInitialFiles']();
}

export function GetWorkspaceInfo() {
  return window['go']['main']['App']['GetWorkspaceInfo']();
}

export function LoadSession() {
  return window['go']['main']['App']['LoadSession']();
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function PrintDocument() {
  return window['go']['main']['App']['PrintDocument']();
}

export function ReadDirectoryTree(arg1, arg2) {
  return window['go']['main']['App']['ReadDirectoryTree'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SavePastedImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePastedImage'](arg1, arg2, arg3);
}

export function SaveSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2, arg3);
}

export function UnwatchFile(arg1) {
  return window['go']['main']['App']['UnwatchFile'](arg1);
}

export function WatchFile(arg1) {
  return window['go']['main']['App']['WatchFile'](arg1);
}
