// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInitialFiles():Promise<Array<string>>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<main.FileInfo>;

export function SaveFile(arg1:string,arg2:string):Promise<main.FileInfo>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function UnwatchFile(arg1:string):Promise<void>;

export function WatchFile(arg1:string):Promise<void>;
