// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewFile(arg1, arg2) {
  return window['go']['main']['App']['CreateNewFile'](arg1, arg2);
}

export function GetInitialFiles() {
  return window['go']['main']['App']['GetInitialFiles']();
}

export function GetWorkspaceInfo() {
  return window['go']['main']['App']['GetWorkspaceInfo']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadDirectoryTree(arg1, arg2) {
  return window['go']['main']['App']['ReadDirectoryTree'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function UnwatchFile(arg1) {
  return window['go']['main']['App']['UnwatchFile'](arg1);
}

export function WatchFile(arg1) {
  return window['go']['main']['App']['WatchFile'](arg1);
}
